name: Manual Docker Build and Push

on:
  workflow_dispatch:  # Ermöglicht manuelle Auslösung über GitHub UI
    inputs:
      tag:
        description: 'Custom tag (optional, defaults to latest)'
        required: false
        default: 'latest'
        type: string

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}
          
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ secrets.DOCKER_USERNAME }}/paperless-ai
            ghcr.io/${{ github.repository_owner }}/paperless-ai
          tags: |
            type=raw,value=${{ inputs.tag }}
            type=sha,prefix={{branch}}-
            
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          
      - name: Summary
        run: |
          echo "## 🚀 Docker Build Complete" >> $GITHUB_STEP_SUMMARY
          echo "Successfully built and pushed Docker images with tag: **${{ inputs.tag }}**" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Images pushed to:" >> $GITHUB_STEP_SUMMARY
          echo "- Docker Hub: \`${{ secrets.DOCKER_USERNAME }}/paperless-ai:${{ inputs.tag }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- GitHub Container Registry: \`ghcr.io/${{ github.repository_owner }}/paperless-ai:${{ inputs.tag }}\`" >> $GITHUB_STEP_SUMMARY
